locking down semantic version for minor updates
getting an error during build, because of spread operator from ES6 upgrade

ui/node_modules/chalk/source/index.js:106
1387 ...styles,
1388 ^^^
1389
1390SyntaxError: Unexpected token ...